
CREATE TABLE entidad_federativa (
  id_entidad     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador único
  nombre_entidad VARCHAR(50) NOT NULL UNIQUE,							-- Nombre del estado
  abreviatura    VARCHAR(5)  NOT NULL UNIQUE							-- Abreviatura oficial
);

INSERT INTO entidad_federativa (nombre_entidad, abreviatura) VALUES					
('Aguascalientes','AGS'),					
('Baja California','BC'),					
('Baja California Sur','BCS'),					
('Campeche','CAMP'),					
('Coahuila','COAH'),					
('Colima','COL'),					
('Chiapas','CHIS'),					
('Chihuahua','CHIH'),					
('Ciudad de México','CDMX'),					
('Durango','DGO'),					
('Guanajuato','GTO'),					
('Guerrero','GRO'),					
('Hidalgo','HGO'),					
('Jalisco','JAL'),					
('Estado de México','MEX'),					
('Michoacán','MICH'),					
('Morelos','MOR'),					
('Nayarit','NAY'),					
('Nuevo León','NL'),					
('Oaxaca','OAX'),					
('Puebla','PUE'),					
('Querétaro','QRO'),					
('Quintana Roo','QROO'),					
('San Luis Potosí','SLP'),					
('Sinaloa','SIN'),					
('Sonora','SON'),					
('Tabasco','TAB'),					
('Tamaulipas','TAMPS'),					
('Tlaxcala','TLAX'),					
('Veracruz','VER'),
('Yucatán','YUC'),
('Zacatecas','ZAC');


-- ---------------------------------------------------------
-- Tabla: alumno
-- Contiene la información personal y académica básica de los alumnos inscritos en la institución.
-- ---------------------------------------------------------

CREATE TABLE alumno (
  numero_cuenta      INT PRIMARY KEY,				-- Número único del alumno
  nombre             VARCHAR(25) NOT NULL,			-- Nombre(s)
  apellido_paterno   VARCHAR(25) NOT NULL,			-- Apellido paterno
  apellido_materno   VARCHAR(25) NOT NULL,			-- Apellido materno
  curp               CHAR(18)    NOT NULL UNIQUE,	-- CURP del alumno
  telefono           CHAR(10)    NOT NULL,			-- Teléfono de contacto
  sexo               CHAR(1)     NOT NULL,			-- Sexo (M/F)
  correo_electronico VARCHAR(100) NOT NULL UNIQUE,	-- Correo institucional/personal
  fecha_nacimiento   DATE        NOT NULL,			-- Fecha de nacimiento
  foto_perfil        BYTEA NULL,                    -- Fotografía del alumno, imagen/binario (punto 7)
  id_entidad         INT         NOT NULL,			-- Entidad federativa de origen

-- Restricciones de validación
  CONSTRAINT ck_alumno_sexo CHECK (sexo IN ('M','F')),
  CONSTRAINT ck_alumno_tel  CHECK (telefono ~ '^[0-9]{10}$'),

-- Relación con entidad_federativa
  CONSTRAINT fk_alumno_entidad
    FOREIGN KEY (id_entidad)
    REFERENCES entidad_federativa(id_entidad)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


INSERT INTO alumno										
(numero_cuenta, nombre, apellido_paterno, apellido_materno, curp, telefono, sexo, correo_electronico, fecha_nacimiento, id_entidad)										
VALUES										
(320267695, 'Ana', 'Gómez', 'Pérez', 'GOPA000101MDFRZN01', '5510000001', 'F', 'ana.gomez@gmail.com', '2001-05-12', 9),										
(320267696, 'Luis', 'Martínez', 'López', 'MALL000102HDFRZN02', '5510000002', 'M', 'luis.martinez@gmail.com', '2000-09-22', 15),										
(320267697, 'Valeria', 'Mejía', 'Osornio', 'MEOV000103MDFRZN03', '5510000003', 'F', 'valeria.mejia@gmail.com', '2003-03-15', 14),										
(320267698, 'Randy', 'Romero', 'Palacios', 'RORP000104HDFRZN04', '5510000004', 'M', 'randy.romero@gmail.com', '2002-12-04', 19),										
(320267699, 'Bryan', 'Laurrabaquio', 'Ramírez', 'LARB000105HDFRZN05', '5510000005', 'M', 'bryan.laurrabaquio@gmail.com', '2002-07-09', 9),										
(320267700, 'André', 'Contreras', 'González', 'COGA000106HDFRZN06', '5510000006', 'M', 'andre.contreras@gmail.com', '2004-11-17', 11),										
(320267701, 'Sofía', 'Hernández', 'Castro', 'HECS000107MDFRZN07', '5510000007', 'F', 'sofia.hernandez@gmail.com', '2003-04-02', 13),										
(320267702, 'Emilia', 'Santos', 'Luna', 'SALU000108MDFRZN08', '5510000008', 'F', 'emilia.santos@gmail.com', '2000-10-20', 7),										
(320267703, 'Emanuel', 'Villanueva', 'García', 'VIGE000109HDFRZN09', '5510000009', 'M', 'emanuel.villanueva@gmail.com', '2001-08-28', 9),										
(320267704, 'Daniela', 'Flores', 'García', 'FOGA000110MDFRZN10', '5510000010', 'F', 'daniela.flores@gmail.com', '2004-01-30', 10),										
(320267705, 'Marco', 'Navarro', 'Jiménez', 'NAJM000111HDFRZN11', '5510000011', 'M', 'marco.navarro@gmail.com', '2003-06-16', 12),										
(320267706, 'Camila', 'Vargas', 'Reyes', 'VARE000112MDFRZN12', '5510000012', 'F', 'camila.vargas@gmail.com', '2002-02-08', 13),										
(320267707, 'Carlos', 'Hernández', 'Guzmán', 'HEGC000113HDFRZN13', '5510000013', 'M', 'carlos.hernandez@gmail.com', '2000-03-14', 14),										
(320267708, 'Fernanda', 'Díaz', 'Moreno', 'DIMO000114MDFRZN14', '5510000014', 'F', 'fernanda.diaz@gmail.com', '2001-07-09', 15),										
(320267709, 'Diego', 'Reyes', 'Salinas', 'RESA000115HDFRZN15', '5510000015', 'M', 'diego.reyes@gmail.com', '2002-10-25', 16),										
(320267710, 'Natalia', 'García', 'Ramírez', 'GARA000116MDFRZN16', '5510000016', 'F', 'natalia.garcia@gmail.com', '2004-09-12', 17),										
(320267711, 'Rodrigo', 'Torres', 'Mendoza', 'TOME000117HDFRZN17', '5510000017', 'M', 'rodrigo.torres@gmail.com', '2003-06-18', 18),										
(320267712, 'Elena', 'Pérez', 'Cano', 'PECE000118MDFRZN18', '5510000018', 'F', 'elena.perez@gmail.com', '2000-05-05', 19),										
(320267713, 'Miguel', 'Zapata', 'Luna', 'ZALM000119HDFRZN19', '5510000019', 'M', 'miguel.zapata@gmail.com', '2001-04-27', 20),										
(320267714, 'Lucía', 'Rivera', 'Ortiz', 'RIOL000120MDFRZN20', '5510000020', 'F', 'lucia.rivera@gmail.com', '2000-02-14', 21),										
(320267715, 'Ángel', 'Jiménez', 'Flores', 'JIFA000121HDFRZN21', '5510000021', 'M', 'angel.jimenez@gmail.com', '2002-11-02', 22),										
(320267716, 'Regina', 'Campos', 'Vega', 'CAVE000122MDFRZN22', '5510000022', 'F', 'regina.campos@gmail.com', '2003-01-09', 23),										
(320267717, 'Eduardo', 'Ortega', 'Sánchez', 'ORSA000123HDFRZN23', '5510000023', 'M', 'eduardo.ortega@gmail.com', '2001-07-19', 24),										
(320267718, 'Mariana', 'Hernández', 'Núñez', 'HENU000124MDFRZN24', '5510000024', 'F', 'mariana.hernandez@gmail.com', '2000-12-20', 25),										
(320267719, 'Jorge', 'Ramírez', 'Morales', 'RAMJ000125HDFRZN25', '5510000025', 'M', 'jorge.ramirez@gmail.com', '2004-02-22', 26),										
(320267720, 'Andrea', 'Cortés', 'Lara', 'COLA000126MDFRZN26', '5510000026', 'F', 'andrea.cortes@gmail.com', '2001-03-11', 27),										
(320267721, 'Sebastián', 'García', 'León', 'GALE000127HDFRZN27', '5510000027', 'M', 'sebastian.garcia@gmail.com', '2002-09-10', 28),										
(320267722, 'Isabela', 'Mendoza', 'Pérez', 'MEPE000128MDFRZN28', '5510000028', 'F', 'isabela.mendoza@gmail.com', '2003-07-05', 29),										
(320267723, 'Héctor', 'González', 'Muñoz', 'GOMH000129HDFRZN29', '5510000029', 'M', 'hector.gonzalez@gmail.com', '2000-01-14', 30),										
(320267724, 'Julia', 'Ramírez', 'Gómez', 'RAGJ000130MDFRZN30', '5510000030', 'F', 'julia.ramirez@gmail.com', '2001-09-25', 31),										
(320267725, 'Mateo', 'Salazar', 'Vargas', 'SAVM000131HDFRZN31', '5510000031', 'M', 'mateo.salazar@gmail.com', '2003-10-01', 32),										
(320267726, 'Paola', 'Flores', 'Román', 'FLRP000132MDFRZN32', '5510000032', 'F', 'paola.flores@gmail.com', '2001-12-17', 1),										
(320267727, 'Leonardo', 'Luna', 'Castillo', 'LUCL000133HDFRZN33', '5510000033', 'M', 'leonardo.luna@gmail.com', '2002-11-20', 2),										
(320267728, 'Monserrat', 'Ruiz', 'López', 'RULO000134MDFRZN34', '5510000034', 'F', 'monserrat.ruiz@gmail.com', '2000-04-10', 3),										
(320267729, 'Tomás', 'Aguilar', 'Reyes', 'AGRT000135HDFRZN35', '5510000035', 'M', 'tomas.aguilar@gmail.com', '2003-09-06', 4),										
(320267730, 'Jimena', 'Silva', 'Nava', 'SINA000136MDFRZN36', '5510000036', 'F', 'jimena.silva@gmail.com', '2002-03-08', 5),										
(320267731, 'Iván', 'Castro', 'Mendoza', 'CAMI000137HDFRZN37', '5510000037', 'M', 'ivan.castro@gmail.com', '2000-06-13', 6),										
(320267732, 'Elisa', 'Domínguez', 'López', 'DOLE000138MDFRZN38', '5510000038', 'F', 'elisa.dominguez@gmail.com', '2001-02-02', 7),										
(320267733, 'Juan', 'Pineda', 'Gómez', 'PIGJ000139HDFRZN39', '5510000039', 'M', 'juan.pineda@gmail.com', '2004-08-29', 8),										
(320267734, 'Alejandra', 'Santos', 'Reyes', 'SARE000140MDFRZN40', '5510000040', 'F', 'alejandra.santos@gmail.com', '2003-11-10', 9),										
(320267735, 'David', 'Torres', 'Camacho', 'TOCD000141HDFRZN41', '5510000041', 'M', 'david.torres@gmail.com', '2001-03-14', 10),										
(320267736, 'Carolina', 'Morales', 'Jiménez', 'MOJC000142MDFRZN42', '5510000042', 'F', 'carolina.morales@gmail.com', '2000-05-05', 11),										
(320267737, 'Santiago', 'Ortiz', 'Navarro', 'ORNS000143HDFRZN43', '5510000043', 'M', 'santiago.ortiz@gmail.com', '2003-07-26', 12),										
(320267738, 'María', 'Vega', 'Cruz', 'VECR000144MDFRZN44', '5510000044', 'F', 'maria.vega@gmail.com', '2002-12-01', 13),										
(320267739, 'Gabriel', 'Ruiz', 'Santos', 'RUSA000145HDFRZN45', '5510000045', 'M', 'gabriel.ruiz@gmail.com', '2004-02-11', 14),										
(320267740, 'Renata', 'Cano', 'Rojas', 'CARO000146MDFRZN46', '5510000046', 'F', 'renata.cano@gmail.com', '2001-10-15', 15),										
(320267741, 'Emilio', 'Vázquez', 'López', 'VALO000147HDFRZN47', '5510000047', 'M', 'emilio.vazquez@gmail.com', '2002-06-28', 16),										
(320267742, 'Claudia', 'López', 'Morales', 'LOMC000148MDFRZN48', '5510000048', 'F', 'claudia.lopez@gmail.com', '2000-09-03', 17),										
(320267743, 'Mauricio', 'Jiménez', 'Salas', 'JISA000149HDFRZN49', '5510000049', 'M', 'mauricio.jimenez@gmail.com', '2001-01-27', 18),										
(320267744, 'Ángela', 'Mora', 'Campos', 'MOCA000150MDFRZN50', '5510000050', 'F', 'angela.mora@gmail.com', '2003-12-23', 19),										
(320267745, 'Manuel', 'Ortega', 'Pérez', 'ORPM000151HDFRZN51', '5510000051', 'M', 'manuel.ortega@gmail.com', '2001-02-10', 20),										
(320267746, 'Patricia', 'García', 'Sánchez', 'GASP000152MDFRZN52', '5510000052', 'F', 'patricia.garcia@gmail.com', '2003-05-25', 21),										
(320267747, 'Alberto', 'Luna', 'Reyes', 'LURE000153HDFRZN53', '5510000053', 'M', 'alberto.luna@gmail.com', '2002-11-04', 22),										
(320267748, 'Romina', 'Cruz', 'Hernández', 'CRHR000154MDFRZN54', '5510000054', 'F', 'romina.cruz@gmail.com', '2004-09-17', 23),										
(320267749, 'Ricardo', 'Soto', 'Jiménez', 'SOJR000155HDFRZN55', '5510000055', 'M', 'ricardo.soto@gmail.com', '2001-06-08', 24),										
(320267750, 'Isabella', 'Méndez', 'Torres', 'METI000156MDFRZN56', '5510000056', 'F', 'isabella.mendez@gmail.com', '2002-07-19', 25),										
(320267751, 'Alejandro', 'Ramírez', 'Domínguez', 'RADA000157HDFRZN57', '5510000057', 'M', 'alejandro.ramirez@gmail.com', '2003-10-21', 26),										
(320267752, 'Natalia', 'Suárez', 'Morales', 'SUMN000158MDFRZN58', '5510000058', 'F', 'natalia.suarez@gmail.com', '2000-04-04', 27),										
(320267753, 'Javier', 'Pérez', 'Vega', 'PEVJ000159HDFRZN59', '5510000059', 'M', 'javier.perez@gmail.com', '2001-03-22', 28),										
(320267754, 'Ximena', 'Aguilar', 'López', 'AGLX000160MDFRZN60', '5510000060', 'F', 'ximena.aguilar@gmail.com', '2002-09-15', 29),										
(320267755, 'Raúl', 'Vázquez', 'Luna', 'VALR000161HDFRZN61', '5510000061', 'M', 'raul.vazquez@gmail.com', '2000-01-12', 30),										
(320267756, 'Mónica', 'Cortés', 'Navarro', 'CONM000162MDFRZN62', '5510000062', 'F', 'monica.cortes@gmail.com', '2004-03-05', 31),										
(320267757, 'Óscar', 'López', 'Jiménez', 'LOJO000163HDFRZN63', '5510000063', 'M', 'oscar.lopez@gmail.com', '2003-12-16', 32),										
(320267758, 'Carla', 'Jiménez', 'Campos', 'JICA000164MDFRZN64', '5510000064', 'F', 'carla.jimenez@gmail.com', '2002-06-02', 1),										
(320267759, 'Hugo', 'Núñez', 'Cruz', 'NUCH000165HDFRZN65', '5510000065', 'M', 'hugo.nunez@gmail.com', '2001-05-19', 2),										
(320267760, 'Alejandra', 'Moreno', 'Pineda', 'MOPA000166MDFRZN66', '5510000066', 'F', 'alejandra.moreno@gmail.com', '2000-07-27', 3),										
(320267761, 'Arturo', 'León', 'Vargas', 'LEVA000167HDFRZN67', '5510000067', 'M', 'arturo.leon@gmail.com', '2002-09-09', 4),										
(320267762, 'Sara', 'Guzmán', 'Orozco', 'GUOS000168MDFRZN68', '5510000068', 'F', 'sara.guzman@gmail.com', '2001-10-10', 5),										
(320267763, 'Daniel', 'Rojas', 'Ramos', 'RORJ000169HDFRZN69', '5510000069', 'M', 'daniel.rojas@gmail.com', '2004-08-12', 6),										
(320267764, 'Mariana', 'López', 'Rivera', 'LORM000170MDFRZN70', '5510000070', 'F', 'mariana.lopez@gmail.com', '2003-05-07', 7),										
(320267765, 'Fernando', 'Serrano', 'García', 'SEGF000171HDFRZN71', '5510000071', 'M', 'fernando.serrano@gmail.com', '2000-02-14', 8),										
(320267766, 'Claudia', 'Jiménez', 'Torres', 'JICT000172MDFRZN72', '5510000072', 'F', 'claudia.jimenez@gmail.com', '2002-03-29', 9),										
(320267767, 'Joaquín', 'Maldonado', 'Ramírez', 'MARA000173HDFRZN73', '5510000073', 'M', 'joaquin.maldonado@gmail.com', '2001-12-11', 10),										
(320267768, 'Victoria', 'Reyes', 'Lara', 'RELV000174MDFRZN74', '5510000074', 'F', 'victoria.reyes@gmail.com', '2003-01-22', 11),										
(320267769, 'Pablo', 'Aguilar', 'Flores', 'AGFP000175HDFRZN75', '5510000075', 'M', 'pablo.aguilar@gmail.com', '2000-09-18', 12),										
(320267770, 'Montserrat', 'Santos', 'Vega', 'SAVE000176MDFRZN76', '5510000076', 'F', 'montserrat.santos@gmail.com', '2002-06-04', 13),										
(320267771, 'Francisco', 'Cruz', 'Jiménez', 'CRJF000177HDFRZN77', '5510000077', 'M', 'francisco.cruz@gmail.com', '2001-02-26', 14),										
(320267772, 'Elisa', 'Ortega', 'Hernández', 'ORHE000178MDFRZN78', '5510000078', 'F', 'elisa.ortega@gmail.com', '2004-10-19', 15),										
(320267773, 'Ricardo', 'Vega', 'Ramírez', 'VERI000179HDFRZN79', '5510000079', 'M', 'ricardo.vega@gmail.com', '2000-07-08', 16),										
(320267774, 'Regina', 'Jiménez', 'Luna', 'JILR000180MDFRZN80', '5510000080', 'F', 'regina.jimenez@gmail.com', '2001-08-20', 17),										
(320267775, 'Alan', 'Torres', 'Cruz', 'TOCA000181HDFRZN81', '5510000081', 'M', 'alan.torres@gmail.com', '2002-05-15', 18),										
(320267776, 'Pamela', 'Morales', 'Vega', 'MOVE000182MDFRZN82', '5510000082', 'F', 'pamela.morales@gmail.com', '2000-12-12', 19),										
(320267777, 'Iván', 'Gómez', 'Santos', 'GOSI000183HDFRZN83', '5510000083', 'M', 'ivan.gomez@gmail.com', '2003-03-23', 20),										
(320267778, 'Natalia', 'Lara', 'Hernández', 'LAHN000184MDFRZN84', '5510000084', 'F', 'natalia.lara@gmail.com', '2001-04-08', 21),										
(320267779, 'Héctor', 'Navarro', 'Jiménez', 'NAJH000185HDFRZN85', '5510000085', 'M', 'hector.navarro@gmail.com', '2004-02-05', 22),										
(320267780, 'María', 'Campos', 'Cruz', 'CAMA000186MDFRZN86', '5510000086', 'F', 'maria.campos@gmail.com', '2003-09-29', 23),										
(320267781, 'Cristian', 'Reyes', 'Pérez', 'REPC000187HDFRZN87', '5510000087', 'M', 'cristian.reyes@gmail.com', '2000-11-11', 24),										
(320267782, 'Julia', 'Domínguez', 'Flores', 'DOFJ000188MDFRZN88', '5510000088', 'F', 'julia.dominguez@gmail.com', '2001-06-27', 25),										
(320267783, 'Andrés', 'Vázquez', 'Soto', 'VASO000189HDFRZN89', '5510000089', 'M', 'andres.vazquez@gmail.com', '2002-07-30', 26),										
(320267784, 'Adriana', 'Salinas', 'López', 'SALO000190MDFRZN90', '5510000090', 'F', 'adriana.salinas@gmail.com', '2004-03-14', 27),										
(320267785, 'Raúl', 'Zamora', 'García', 'ZAGR000191HDFRZN91', '5510000091', 'M', 'raul.zamora@gmail.com', '2001-10-03', 28),										
(320267786, 'Elena', 'Mejía', 'Reyes', 'MERE000192MDFRZN92', '5510000092', 'F', 'elena.mejia@gmail.com', '2000-01-09', 29),										
(320267787, 'Felipe', 'Romero', 'Vega', 'ROVF000193HDFRZN93', '5510000093', 'M', 'felipe.romero@gmail.com', '2003-08-17', 30),										
(320267788, 'Rosa', 'García', 'Torres', 'GATR000194MDFRZN94', '5510000094', 'F', 'rosa.garcia@gmail.com', '2002-10-21', 31),										
(320267789, 'José', 'Cano', 'Flores', 'CAFO000195HDFRZN95', '5510000095', 'M', 'jose.cano@gmail.com', '2004-06-09', 32),										
(320267790, 'Verónica', 'López', 'Díaz', 'LODV000196MDFRZN96', '5510000096', 'F', 'veronica.lopez@gmail.com', '2000-05-03', 1),										
(320267791, 'Mario', 'Cruz', 'Mendoza', 'CRMM000197HDFRZN97', '5510000097', 'M', 'mario.cruz@gmail.com', '2001-11-27', 2),										
(320267792, 'Lucía', 'Pérez', 'Reyes', 'PERE000198MDFRZN98', '5510000098', 'F', 'lucia.perez@gmail.com', '2002-01-30', 3),										
(320267793, 'Eduardo', 'Mora', 'Cervantes', 'MOCE000199HDFRZN99', '5510000099', 'M', 'eduardo.mora@gmail.com', '2003-09-14', 4),										
(320267794, 'Fernanda', 'Zúñiga', 'Soto', 'ZUSF000200MDFRZN00', '5510000100', 'F', 'fernanda.zuniga@gmail.com', '2001-03-06', 5),										
(320267795, 'Adrián', 'Morales', 'Pérez', 'MOPE000201HDFRZN01', '5510000101', 'M', 'adrian.morales@gmail.com', '2000-04-08', 6),										
(320267796, 'Camila', 'Jiménez', 'Ramírez', 'JIRA000202MDFRZN02', '5510000102', 'F', 'camila.jimenez@gmail.com', '2003-06-17', 7),										
(320267797, 'Emilio', 'Lara', 'Vega', 'LAVE000203HDFRZN03', '5510000103', 'M', 'emilio.lara@gmail.com', '2001-10-23', 8),										
(320267798, 'María', 'Castillo', 'Cruz', 'CACM000204MDFRZN04', '5510000104', 'F', 'maria.castillo@gmail.com', '2002-02-02', 9),										
(320267799, 'Rodrigo', 'Nava', 'González', 'NAGR000205HDFRZN05', '5510000105', 'M', 'rodrigo.nava@gmail.com', '2004-05-12', 10),										
(320267800, 'Diana', 'Serrano', 'Flores', 'SEFD000206MDFRZN06', '5510000106', 'F', 'diana.serrano@gmail.com', '2000-12-11', 11),										
(320267801, 'Miguel', 'Campos', 'Jiménez', 'CAJM000207HDFRZN07', '5510000107', 'M', 'miguel.campos@gmail.com', '2003-09-22', 12),										
(320267802, 'Lucía', 'Ortega', 'Vargas', 'ORVL000208MDFRZN08', '5510000108', 'F', 'lucia.ortega@gmail.com', '2001-07-06', 13),										
(320267803, 'Eduardo', 'Reyes', 'Salinas', 'RESA000209HDFRZN09', '5510000109', 'M', 'eduardo.reyes@gmail.com', '2002-04-13', 14),										
(320267804, 'Elena', 'García', 'Romero', 'GARL000210MDFRZN10', '5510000110', 'F', 'elena.garcia@gmail.com', '2004-01-25', 15),										
(320267805, 'Iván', 'Torres', 'Morales', 'TOMI000211HDFRZN11', '5510000111', 'M', 'ivan.torres@gmail.com', '2000-09-01', 16),										
(320267806, 'Alejandra', 'López', 'Vega', 'LOVE000212MDFRZN12', '5510000112', 'F', 'alejandra.lopez@gmail.com', '2003-03-08', 17),										
(320267807, 'Pablo', 'Jiménez', 'Hernández', 'JIHP000213HDFRZN13', '5510000113', 'M', 'pablo.jimenez@gmail.com', '2002-07-29', 18),										
(320267808, 'Clara', 'Hernández', 'Soto', 'HESC000214MDFRZN14', '5510000114', 'F', 'clara.hernandez@gmail.com', '2001-11-04', 19),										
(320267809, 'Fernando', 'Aguilar', 'Cano', 'AGCF000215HDFRZN15', '5510000115', 'M', 'fernando.aguilar@gmail.com', '2003-10-22', 20),										
(320267810, 'Paola', 'Cruz', 'Navarro', 'CRNP000216MDFRZN16', '5510000116', 'F', 'paola.cruz@gmail.com', '2004-02-07', 21),										
(320267811, 'Santiago', 'Romero', 'Luna', 'ROLS000217HDFRZN17', '5510000117', 'M', 'santiago.romero@gmail.com', '2000-12-19', 22),										
(320267812, 'Mariana', 'Vega', 'Ramos', 'VERM000218MDFRZN18', '5510000118', 'F', 'mariana.vega@gmail.com', '2001-08-24', 23),										
(320267813, 'Héctor', 'Mendoza', 'Campos', 'MECH000219HDFRZN19', '5510000119', 'M', 'hector.mendoza@gmail.com', '2003-01-28', 24),										
(320267814, 'Regina', 'Salas', 'Hernández', 'SAHR000220MDFRZN20', '5510000120', 'F', 'regina.salas@gmail.com', '2002-09-12', 25),										
(320267815, 'José', 'Jiménez', 'Pérez', 'JIPE000221HDFRZN21', '5510000121', 'M', 'jose.jimenez@gmail.com', '2000-05-17', 26),										
(320267816, 'Patricia', 'González', 'Reyes', 'GORE000222MDFRZN22', '5510000122', 'F', 'patricia.gonzalez@gmail.com', '2001-03-09', 27),										
(320267817, 'Luis', 'Santos', 'Moreno', 'SAMU000223HDFRZN23', '5510000123', 'M', 'luis.santos@gmail.com', '2002-07-15', 28),										
(320267818, 'María', 'Ramírez', 'Ortega', 'RAOM000224MDFRZN24', '5510000124', 'F', 'maria.ramirez@gmail.com', '2004-06-25', 29),										
(320267819, 'Javier', 'Flores', 'Salinas', 'FOSJ000225HDFRZN25', '5510000125', 'M', 'javier.flores@gmail.com', '2003-02-03', 30),										
(320267820, 'Carolina', 'Cano', 'López', 'CALC000226HDFRZN26', '5510000126', 'F', 'carolina.cano@gmail.com', '2001-09-29', 31),										
(320267821, 'Arturo', 'Reyes', 'Jiménez', 'REJA000227HDFRZN27', '5510000127', 'M', 'arturo.reyes@gmail.com', '2000-01-06', 32),										
(320267822, 'Elisa', 'Zúñiga', 'Nava', 'ZUNE000228MDFRZN28', '5510000128', 'F', 'elisa.zuniga@gmail.com', '2002-10-18', 1),										
(320267823, 'Rubén', 'Mora', 'Hernández', 'MOHR000229HDFRZN29', '5510000129', 'M', 'ruben.mora@gmail.com', '2003-12-08', 2),										
(320267824, 'Valeria', 'Campos', 'Torres', 'CATO000230MDFRZN30', '5510000130', 'F', 'valeria.campos@gmail.com', '2001-06-02', 3),										
(320267825, 'Óscar', 'Vega', 'Ruiz', 'VERO000231HDFRZN31', '5510000131', 'M', 'oscar.vega@gmail.com', '2000-08-23', 4),										
(320267826, 'Daniela', 'López', 'Gómez', 'LOGD000232MDFRZN32', '5510000132', 'F', 'daniela.lopez@gmail.com', '2004-01-20', 5),										
(320267827, 'Emilio', 'Aguilar', 'Jiménez', 'AGJE000233HDFRZN33', '5510000133', 'M', 'emilio.aguilar@gmail.com', '2002-02-22', 6),										
(320267828, 'Lucía', 'Ortega', 'Flores', 'ORFL000234MDFRZN34', '5510000134', 'F', 'lucia.orteg@gmail.com', '2001-11-05', 7),										
(320267829, 'Fernando', 'Cruz', 'García', 'CRGF000235HDFRZN35', '5510000135', 'M', 'fernando.cruz@gmail.com', '2003-09-17', 8),										
(320267830, 'Paula', 'Ramírez', 'Núñez', 'RANP000236MDFRZN36', '5510000136', 'F', 'paula.ramirez@gmail.com', '2000-07-09', 9),										
(320267831, 'Hugo', 'Jiménez', 'Morales', 'JIMH000237HDFRZN37', '5510000137', 'M', 'hugo.jimenez@gmail.com', '2004-03-24', 10),										
(320267832, 'Regina', 'López', 'Salas', 'LOSR000238MDFRZN38', '5510000138', 'F', 'regina.lopez@gmail.com', '2001-05-30', 11),										
(320267833, 'Luis', 'Campos', 'Hernández', 'CAHL000239HDFRZN39', '5510000139', 'M', 'luis.campos@gmail.com', '2003-01-13', 12),										
(320267834, 'Mónica', 'Reyes', 'Jiménez', 'REJM000240MDFRZN40', '5510000140', 'F', 'monica.reyes@gmail.com', '2000-09-10', 13),										
(320267835, 'Iván', 'Ortega', 'Ramírez', 'ORRI000241HDFRZN41', '5510000141', 'M', 'ivan.ortega@gmail.com', '2002-12-21', 14),										
(320267836, 'Elena', 'Torres', 'Flores', 'TOFE000242MDFRZN42', '5510000142', 'F', 'elena.torres@gmail.com', '2001-06-25', 15),										
(320267837, 'Mario', 'González', 'Vega', 'GOVE000243HDFRZN43', '5510000143', 'M', 'mario.gonzalez@gmail.com', '2003-08-03', 16),										
(320267838, 'Renata', 'Jiménez', 'Pérez', 'JIPE000244MDFRZN44', '5510000144', 'F', 'renata.jimenez@gmail.com', '2000-04-16', 17),										
(320267839, 'José', 'Serrano', 'López', 'SELO000245HDFRZN45', '5510000145', 'M', 'jose.serrano@gmail.com', '2004-07-01', 18),										
(320267840, 'Carla', 'Vega', 'Ruiz', 'VERC000246MDFRZN46', '5510000146', 'F', 'carla.vega@gmail.com', '2002-11-12', 19),										
(320267841, 'Raúl', 'Flores', 'Pérez', 'FOPR000247HDFRZN47', '5510000147', 'M', 'raul.flores@gmail.com', '2001-03-28', 20),										
(320267842, 'Isabela', 'Cruz', 'Ramírez', 'CRRI000248MDFRZN48', '5510000148', 'F', 'isabela.cruz@gmail.com', '2003-09-09', 21),										
(320267843, 'Daniel', 'Hernández', 'Santos', 'HESA000249HDFRZN49', '5510000149', 'M', 'daniel.hernandez@gmail.com', '2000-06-04', 22),										
(320267844, 'Natalia', 'Moreno', 'Gómez', 'MOGN000250MDFRZN50', '5510000150', 'F', 'natalia.moreno@gmail.com', '2004-05-26', 23);										





-- ---------------------------------------------------------
-- Tabla: profesor
-- Almacena la información personal, laboral y salarial de los profesores que imparten cursos en la institución.
-- Incluye un campo JSONB para mantener un snapshot completo del registro del profesor. 
-- ---------------------------------------------------------

CREATE TABLE profesor (
  id_profesor        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador único del profesor
  nombre             VARCHAR(25) NOT NULL,								-- Nombre(s)
  apellido_paterno   VARCHAR(25) NOT NULL,								-- Apellido paterno
  apellido_materno   VARCHAR(25) NOT NULL,								-- Apellido materno
  curp               CHAR(18)    NOT NULL UNIQUE,						-- CURP del profesor
  rfc                CHAR(13)    NOT NULL UNIQUE,						-- RFC fiscal
  telefono           CHAR(10)    NOT NULL,								-- Teléfono de contacto
  sexo               CHAR(1)     NOT NULL,								-- Sexo (M/F)
  correo_electronico VARCHAR(100) NOT NULL UNIQUE,						-- Correo electrónico
  fecha_nacimiento   DATE        NOT NULL,								-- Fecha de nacimiento
  sueldo             NUMERIC(10,2) NOT NULL,							-- Sueldo del profesor
  all_data_professor JSONB NOT NULL DEFAULT '{}'::jsonb,				-- Snapshot JSON del registro
  
  -- Restricciones de validación
  CONSTRAINT ck_profesor_sexo   CHECK (sexo IN ('M','F')),
  CONSTRAINT ck_profesor_tel    CHECK (telefono ~ '^[0-9]{10}$'),
  CONSTRAINT ck_profesor_sueldo CHECK (sueldo >= 0)
);


INSERT INTO profesor (nombre, apellido_paterno, apellido_materno, curp, rfc, telefono, sexo, correo_electronico, fecha_nacimiento, sueldo)												
VALUES												
('María', 'López', 'García', 'LOGM700101MDFRZN01', 'LOGM700101A01', '5510000001', 'F', 'maria.lopez@gmail.com', '1970-01-01', 42000.50),												
('José', 'Martínez', 'Hernández', 'MAHJ680202HDFRZN02', 'MAHJ680202B02', '5510000002', 'M', 'jose.martinez@gmail.com', '1968-02-02', 55000),												
('Guadalupe', 'Hernández', 'Ruiz', 'HERG750303MDFRZN03', 'HERG750303C03', '5510000003', 'F', 'guadalupe.hernandez@gmail.com', '1975-03-03', 39500.25),												
('Carlos', 'Gómez', 'Sánchez', 'GOSC720404HDFRZN04', 'GOSC720404D04', '5510000004', 'M', 'carlos.gomez@gmail.com', '1972-04-04', 51000),												
('Rosa', 'Pérez', 'Luna', 'PELJ770505MDFRZN05', 'PELJ770505E05', '5510000005', 'F', 'rosa.perez@gmail.com', '1977-05-05', 36000.75),												
('Luis', 'Rodríguez', 'Mendoza', 'ROML800606HDFRZN06', 'ROML800606F06', '5510000006', 'M', 'luis.rodriguez@gmail.com', '1980-06-06', 48000),												
('Ana', 'Flores', 'Cruz', 'FOCA850707MDFRZN07', 'FOCA850707G07', '5510000007', 'F', 'ana.flores@gmail.com', '1985-07-07', 33000),												
('Miguel', 'Ramírez', 'Ortega', 'RAOM730808HDFRZN08', 'RAOM730808H08', '5510000008', 'M', 'miguel.ramirez@gmail.com', '1973-08-08', 46000.90),												
('Laura', 'Jiménez', 'Pérez', 'JIPL880909MDFRZN09', 'JIPL880909I09', '5510000009', 'F', 'laura.jimenez@gmail.com', '1988-09-09', 37000),												
('Javier', 'Torres', 'Morales', 'TOMJ710110HDFRZN10', 'TOMJ710110J10', '5510000010', 'M', 'javier.torres@gmail.com', '1971-01-10', 54000),												
('Patricia', 'Vargas', 'Soto', 'VASP900211MDFRZN11', 'VASP900211K11', '5510000011', 'F', 'patricia.vargas@gmail.com', '1990-02-11', 28000),												
('Andrés', 'Navarro', 'Ríos', 'NARA690312HDFRZN12', 'NARA690312L12', '5510000012', 'M', 'andres.navarro@gmail.com', '1969-03-12', 52000),												
('Martha', 'Cruz', 'Díaz', 'CRDM790413MDFRZN13', 'CRDM790413M13', '5510000013', 'F', 'martha.cruz@gmail.com', '1979-04-13', 39000.80),												
('Francisco', 'Ruiz', 'Pérez', 'RUPF810514HDFRZN14', 'RUPF810514N14', '5510000014', 'M', 'francisco.ruiz@gmail.com', '1981-05-14', 43000),												
('Leticia', 'Morales', 'Vega', 'MOVE820615MDFRZN15', 'MOVE820615O15', '5510000015', 'F', 'leticia.morales@gmail.com', '1982-06-15', 32000),												
('Pedro', 'Luna', 'Campos', 'LUCP830716HDFRZN16', 'LUCP830716P16', '5510000016', 'M', 'pedro.luna@gmail.com', '1983-07-16', 47500),												
('Elena', 'García', 'Jiménez', 'GAJE840817MDFRZN17', 'GAJE840817Q17', '5510000017', 'F', 'elena.garcia@gmail.com', '1984-08-17', 35000.50),												
('Fernando', 'Santos', 'León', 'SALE850918HDFRZN18', 'SALE850918R18', '5510000018', 'M', 'fernando.santos@gmail.com', '1985-09-18', 41000),												
('Lucía', 'Reyes', 'Rojas', 'RERL861019MDFRZN19', 'RERL861019S19', '5510000019', 'F', 'lucia.reyes@gmail.com', '1986-10-19', 28000.75),												
('Héctor', 'Ortega', 'Zúñiga', 'ORZH870120HDFRZN20', 'ORZH870120T20', '5510000020', 'M', 'hector.ortega@gmail.com', '1987-01-20', 46000),												
('Alejandra', 'Pineda', 'Castro', 'PICA880221MDFRZN21', 'PICA880221U21', '5510000021', 'F', 'alejandra.pineda@gmail.com', '1988-02-21', 30000),												
('Ricardo', 'Mendoza', 'Ruiz', 'MERR890322HDFRZN22', 'MERR890322V22', '5510000022', 'M', 'ricardo.mendoza@gmail.com', '1989-03-22', 48000.40),												
('Claudia', 'Campos', 'Aguilar', 'CAAC900423MDFRZN23', 'CAAC900423W23', '5510000023', 'F', 'claudia.campos@gmail.com', '1990-04-23', 31000),												
('Roberto', 'Cortés', 'Núñez', 'CONR910524HDFRZN24', 'CONR910524X24', '5510000024', 'M', 'roberto.cortes@gmail.com', '1991-05-24', 34000),												
('Gabriela', 'Delgado', 'Soto', 'DESG920625MDFRZN25', 'DESG920625Y25', '5510000025', 'F', 'gabriela.delgado@gmail.com', '1992-06-25', 26000),												
('Antonio', 'Aguilar', 'Ramos', 'AURA930726HDFRZN26', 'AURA930726Z26', '5510000026', 'M', 'antonio.aguilar@gmail.com', '1993-07-26', 39000),												
('Daniela', 'Hernández', 'Zapata', 'HEZD940827MDFRZN27', 'HEZD940827A27', '5510000027', 'F', 'daniela.hernandez@gmail.com', '1994-08-27', 29000.50),												
('Eduardo', 'Gómez', 'Flores', 'GOFE950928HDFRZN28', 'GOFE950928B28', '5510000028', 'M', 'eduardo.gomez@gmail.com', '1995-09-28', 46000),												
('Paola', 'Jiménez', 'Mora', 'JIMP961029MDFRZN29', 'JIMP961029C29', '5510000029', 'F', 'paola.jimenez@gmail.com', '1996-10-29', 31000),												
('Óscar', 'Romero', 'Torres', 'ROTO971130HDFRZN30', 'ROTO971130D30', '5510000030', 'M', 'oscar.romero@gmail.com', '1997-11-30', 42000.80),												
('Adriana', 'López', 'Cruz', 'LOCA690101MDFRZN31', 'LOCA690101E31', '5510000031', 'F', 'adriana.lopez@gmail.com', '1969-01-01', 52000),												
('Julio', 'Rojas', 'Jiménez', 'ROJJ700202HDFRZN32', 'ROJJ700202F32', '5510000032', 'M', 'julio.rojas@gmail.com', '1970-02-02', 43000),												
('Monserrat', 'Salas', 'Reyes', 'SARM710303MDFRZN33', 'SARM710303G33', '5510000033', 'F', 'monserrat.salas@gmail.com', '1971-03-03', 37000.60),												
('Hugo', 'Carrillo', 'Vega', 'CAVH720404HDFRZN34', 'CAVH720404H34', '5510000034', 'M', 'hugo.carrillo@gmail.com', '1972-04-04', 49000),												
('Beatriz', 'Luna', 'Ramírez', 'LURB730505MDFRZN35', 'LURB730505I35', '5510000035', 'F', 'beatriz.luna@gmail.com', '1973-05-05', 40000),												
('David', 'Morales', 'Campos', 'MOCD740606HDFRZN36', 'MOCD740606J36', '5510000036', 'M', 'david.morales@gmail.com', '1974-06-06', 47000),												
('Sandra', 'Delgado', 'Ruiz', 'DERL750707MDFRZN37', 'DERL750707K37', '5510000037', 'F', 'sandra.delgado@gmail.com', '1975-07-07', 39000.90),												
('Ramiro', 'García', 'Pérez', 'GAPR760808HDFRZN38', 'GAPR760808L38', '5510000038', 'M', 'ramiro.garcia@gmail.com', '1976-08-08', 50000),												
('Cecilia', 'Reyes', 'Ortega', 'REOC770909MDFRZN39', 'REOC770909M39', '5510000039', 'F', 'cecilia.reyes@gmail.com', '1977-09-09', 37000),												
('Ernesto', 'Vega', 'Santos', 'VESR780110HDFRZN40', 'VESR780110N40', '5510000040', 'M', 'ernesto.vega@gmail.com', '1978-01-10', 46000.50),												
('Clara', 'Torres', 'Jiménez', 'TOJC790211MDFRZN41', 'TOJC790211O41', '5510000041', 'F', 'clara.torres@gmail.com', '1979-02-11', 41000),												
('Rafael', 'Núñez', 'Flores', 'NUFR800312HDFRZN42', 'NUFR800312P42', '5510000042', 'M', 'rafael.nunez@gmail.com', '1980-03-12', 50000),												
('Lucero', 'Ramírez', 'Vega', 'RAVL810413MDFRZN43', 'RAVL810413Q43', '5510000043', 'F', 'lucero.ramirez@gmail.com', '1981-04-13', 38000.25),												
('Fernando', 'Ríos', 'Mora', 'RIMF820514HDFRZN44', 'RIMF820514R44', '5510000044', 'M', 'fernando.rios@gmail.com', '1982-05-14', 43000),												
('Rocío', 'Aguilar', 'Campos', 'AGCR830615MDFRZN45', 'AGCR830615S45', '5510000045', 'F', 'rocio.aguilar@gmail.com', '1983-06-15', 35000.60),												
('Ignacio', 'Soto', 'León', 'SOLE840716HDFRZN46', 'SOLE840716T46', '5510000046', 'M', 'ignacio.soto@gmail.com', '1984-07-16', 48000),												
('Gloria', 'Mora', 'Reyes', 'MORE850817MDFRZN47', 'MORE850817U47', '5510000047', 'F', 'gloria.mora@gmail.com', '1985-08-17', 37000.75),												
('Esteban', 'Campos', 'Pérez', 'CAPE860918HDFRZN48', 'CAPE860918V48', '5510000048', 'M', 'esteban.campos@gmail.com', '1986-09-18', 49000),												
('Marisol', 'Hernández', 'Rivas', 'HERM870120MDFRZN49', 'HERM870120W49', '5510000049', 'F', 'marisol.hernandez@gmail.com', '1987-01-20', 36000),												
('Omar', 'Castillo', 'Ruiz', 'CARO880221HDFRZN50', 'CARO880221X50', '5510000050', 'M', 'omar.castillo@gmail.com', '1988-02-21', 47000.40),												
('Liliana', 'Vega', 'Jiménez', 'VEJL890322MDFRZN51', 'VEJL890322A51', '5510000051', 'F', 'liliana.vega@gmail.com', '1989-03-22', 38000),												
('Eduardo', 'Santos', 'Ramírez', 'SARE900423HDFRZN52', 'SARE900423B52', '5510000052', 'M', 'eduardo.santos@gmail.com', '1990-04-23', 43000.50),												
('Patricia', 'Cano', 'Rivas', 'CARP910524MDFRZN53', 'CARP910524C53', '5510000053', 'F', 'patricia.cano@gmail.com', '1991-05-24', 29000),												
('Hugo', 'Delgado', 'Mora', 'DEMH920625HDFRZN54', 'DEMH920625D54', '5510000054', 'M', 'hugo.delgado@gmail.com', '1992-06-25', 47000),												
('Alejandra', 'Aguilar', 'Cruz', 'AGCA930726MDFRZN55', 'AGCA930726E55', '5510000055', 'F', 'alejandra.aguilar@gmail.com', '1993-07-26', 31000.60),												
('Ramiro', 'Ramos', 'Jiménez', 'RAJR940827HDFRZN56', 'RAJR940827F56', '5510000056', 'M', 'ramiro.ramos@gmail.com', '1994-08-27', 49000),												
('Cecilia', 'Hernández', 'Rojas', 'HERC950928MDFRZN57', 'HERC950928G57', '5510000057', 'F', 'cecilia.hernandez@gmail.com', '1995-09-28', 33000.80),												
('Sergio', 'Pérez', 'León', 'PELS961029HDFRZN58', 'PELS961029H58', '5510000058', 'M', 'sergio.perez@gmail.com', '1996-10-29', 41000),												
('Martha', 'Romero', 'Vega', 'ROVM971130MDFRZN59', 'ROVM971130I59', '5510000059', 'F', 'martha.romero@gmail.com', '1997-11-30', 36000),												
('Luis', 'Castillo', 'Salas', 'CASL690101HDFRZN60', 'CASL690101J60', '5510000060', 'M', 'luis.castillo@gmail.com', '1969-01-01', 54000.25),												
('Rosa', 'Ortega', 'Gómez', 'ORGR700202MDFRZN61', 'ORGR700202K61', '5510000061', 'F', 'rosa.ortega@gmail.com', '1970-02-02', 42000),												
('Arturo', 'Morales', 'Ruiz', 'MORA710303HDFRZN62', 'MORA710303L62', '5510000062', 'M', 'arturo.morales@gmail.com', '1971-03-03', 49000.40),												
('Gabriela', 'Reyes', 'Jiménez', 'REJG720404MDFRZN63', 'REJG720404M63', '5510000063', 'F', 'gabriela.reyes@gmail.com', '1972-04-04', 38000),												
('Fernando', 'Sánchez', 'Núñez', 'SANF730505HDFRZN64', 'SANF730505N64', '5510000064', 'M', 'fernando.sanchez@gmail.com', '1973-05-05', 50000),												
('Claudia', 'Campos', 'Torres', 'CATC740606MDFRZN65', 'CATC740606O65', '5510000065', 'F', 'claudia.campo@gmail.com', '1974-06-06', 37000.75),												
('Ricardo', 'Cruz', 'Aguilar', 'CRAR750707HDFRZN66', 'CRAR750707P66', '5510000066', 'M', 'ricardo.cruz@gmail.com', '1975-07-07', 49000),												
('Elena', 'Rivas', 'Flores', 'RIFE760808MDFRZN67', 'RIFE760808Q67', '5510000067', 'F', 'elena.rivas@gmail.com', '1976-08-08', 31000.60),												
('Francisco', 'Domínguez', 'Soto', 'DOSF770909HDFRZN68', 'DOSF770909R68', '5510000068', 'M', 'francisco.dominguez@gmail.com', '1977-09-09', 52000),												
('Lucía', 'Jiménez', 'Luna', 'JILM780110MDFRZN69', 'JILM780110S69', '5510000069', 'F', 'lucia.jimenez@gmail.com', '1978-01-10', 33000.50),												
('Héctor', 'García', 'Reyes', 'GARE790211HDFRZN70', 'GARE790211T70', '5510000070', 'M', 'hector.garcia@gmail.com', '1979-02-11', 46000),												
('Alejandra', 'Pineda', 'Torres', 'PITA800312MDFRZN71', 'PITA800312U71', '5510000071', 'F', 'alejandra.pined@gmail.com', '1980-03-12', 34000.75),												
('Ricardo', 'Mendoza', 'Santos', 'MESA810413HDFRZN72', 'MESA810413V72', '5510000072', 'M', 'ricardo.mendoz@gmail.com', '1981-04-13', 48000),												
('Claudia', 'Campos', 'Jiménez', 'CAJC820514MDFRZN73', 'CAJC820514W73', '5510000073', 'F', 'claudia.camp@gmail.com', '1982-05-14', 35000),												
('Roberto', 'Cortés', 'León', 'COLE830615HDFRZN74', 'COLE830615X74', '5510000074', 'M', 'roberto.corte@gmail.com', '1983-06-15', 42000),												
('Gabriela', 'Delgado', 'Morales', 'DEMG840716MDFRZN75', 'DEMG840716Y75', '5510000075', 'F', 'gabriela.degado@gmail.com', '1984-07-16', 37000.25),												
('Antonio', 'Aguilar', 'Cano', 'AUCN850817HDFRZN76', 'AUCN850817Z76', '5510000076', 'M', 'antonio.aguilr@gmail.com', '1985-08-17', 45000),												
('Daniela', 'Hernández', 'Ruiz', 'HERR870120MDFRZN77', 'HERR870120A77', '5510000077', 'F', 'daniela.hernadez@gmail.com', '1987-01-20', 31000),												
('Eduardo', 'Gómez', 'Castillo', 'GOCE880221HDFRZN78', 'GOCE880221B78', '5510000078', 'M', 'eduardo.gome@gmail.com', '1988-02-21', 47000.80),												
('Paola', 'Jiménez', 'Soto', 'JISP890322MDFRZN79', 'JISP890322C79', '5510000079', 'F', 'paola.jimenz@gmail.com', '1989-03-22', 34000),												
('Óscar', 'Romero', 'Ramos', 'RORO900423HDFRZN80', 'RORO900423D80', '5510000080', 'M', 'oscar.romer@gmail.com', '1990-04-23', 45000.60),												
('Adriana', 'López', 'Torres', 'LOTA910524MDFRZN81', 'LOTA910524E81', '5510000081', 'F', 'adriana.lopz@gmail.com', '1991-05-24', 28000),												
('Julio', 'Rojas', 'Luna', 'ROLU920625HDFRZN82', 'ROLU920625F82', '5510000082', 'M', 'julio.rjas@gmail.com', '1992-06-25', 47000),												
('Monserrat', 'Salas', 'Jiménez', 'SAJM930726MDFRZN83', 'SAJM930726G83', '5510000083', 'F', 'monserrt.salas@gmail.com', '1993-07-26', 31000.40),												
('Hugo', 'Carrillo', 'Reyes', 'CARE940827HDFRZN84', 'CARE940827H84', '5510000084', 'M', 'hugo.carillo@gmail.com', '1994-08-27', 49000),												
('Beatriz', 'Luna', 'Zapata', 'LUZB950928MDFRZN85', 'LUZB950928I85', '5510000085', 'F', 'beatrz.luna@gmail.com', '1995-09-28', 30000),												
('David', 'Morales', 'Campos', 'MOCD961029HDFRZN86', 'MOCD961029J86', '5510000086', 'M', 'david.morles@gmail.com', '1996-10-29', 46000),												
('Sandra', 'Delgado', 'Ortega', 'DEOS971130MDFRZN87', 'DEOS971130K87', '5510000087', 'F', 'sandra.delgad@gmail.com', '1997-11-30', 34000.80),												
('Ramiro', 'García', 'Pineda', 'GAPR680101HDFRZN88', 'GAPR680101L88', '5510000088', 'M', 'ramir.garcia@gmail.com', '1968-01-01', 53000),												
('Cecilia', 'Reyes', 'Zúñiga', 'REZC690202MDFRZN89', 'REZC690202M89', '5510000089', 'F', 'cecili.reyes@gmail.com', '1969-02-02', 38000),												
('Ernesto', 'Vega', 'Campos', 'VECE700303HDFRZN90', 'VECE700303N90', '5510000090', 'M', 'ernest.vega@gmail.com', '1970-03-03', 50000),												
('Clara', 'Torres', 'Salas', 'TOSC710404MDFRZN91', 'TOSC710404O91', '5510000091', 'F', 'clar.torres@gmail.com', '1971-04-04', 37000.70),												
('Rafael', 'Núñez', 'Morales', 'NUMR720505HDFRZN92', 'NUMR720505P92', '5510000092', 'M', 'rafae.nunez@gmail.com', '1972-05-05', 48000),												
('Lucero', 'Ramírez', 'Hernández', 'RAHL730606MDFRZN93', 'RAHL730606Q93', '5510000093', 'F', 'lucer.ramirez@gmail.com', '1973-06-06', 35000),												
('Fernando', 'Ríos', 'Zapata', 'RIZF740707HDFRZN94', 'RIZF740707R94', '5510000094', 'M', 'fernand.rios@gmail.com', '1974-07-07', 46000.90),												
('Rocío', 'Aguilar', 'Luna', 'AGLR750808MDFRZN95', 'AGLR750808S95', '5510000095', 'F', 'roci.aguilar@gmail.com', '1975-08-08', 37000),												
('Ignacio', 'Soto', 'Jiménez', 'SOJI760909HDFRZN96', 'SOJI760909T96', '5510000096', 'M', 'ignaci.soto@gmail.com', '1976-09-09', 48000.75),												
('Gloria', 'Mora', 'Cruz', 'MOCR770110MDFRZN97', 'MOCR770110U97', '5510000097', 'F', 'glori.mora@gmail.com', '1977-01-10', 39000),												
('Esteban', 'Campos', 'Núñez', 'CANH780211HDFRZN98', 'CANH780211V98', '5510000098', 'M', 'esteba.campos@gmail.com', '1978-02-11', 49000.50),												
('Marisol', 'Hernández', 'León', 'HELM790312MDFRZN99', 'HELM790312W99', '5510000099', 'F', 'mariso.hernandez@gmail.com', '1979-03-12', 36000),												
('Omar', 'Castillo', 'Ortega', 'CAOO800413HDFRZN00', 'CAOO800413X00', '5510000100', 'M', 'oma.castillo@gmail.com', '1980-04-13', 47000),												
('Liliana', 'Vega', 'Jiménez', 'VEJL810514MDFRZN10', 'VEJL810514A51', '5510000101', 'F', 'liliana.vega101@gmail.com', '1981-05-14', 38000),												
('Eduardo', 'Santos', 'García', 'SAGE820615HDFRZN10', 'SAGE820615B52', '5510000102', 'M', 'eduardo.santos102@gmail.com', '1982-06-15', 44000.50),												
('Patricia', 'Cano', 'Reyes', 'CARE830716MDFRZN10', 'CARE830716C53', '5510000103', 'F', 'patricia.cano103@gmail.com', '1983-07-16', 29000),												
('Hugo', 'Delgado', 'Flores', 'DEFH840817HDFRZN10', 'DEFH840817D54', '5510000104', 'M', 'hugo.delgado104@gmail.com', '1984-08-17', 47000),												
('Alejandra', 'Aguilar', 'Pérez', 'AGPA850918MDFRZN10', 'AGPA850918E55', '5510000105', 'F', 'alejandra.aguilar105@gmail.com', '1985-09-18', 31000.40),												
('Ramiro', 'Ramos', 'Jiménez', 'RAJR870120HDFRZN10', 'RAJR870120F56', '5510000106', 'M', 'ramiro.ramos106@gmail.com', '1987-01-20', 49000),												
('Cecilia', 'Hernández', 'Nava', 'HENC880221MDFRZN10', 'HENC880221G57', '5510000107', 'F', 'cecilia.hernandez107@gmail.com', '1988-02-21', 33000.75),												
('Sergio', 'Pérez', 'López', 'PELS890322HDFRZN18', 'PELS890322H58', '5510000108', 'M', 'sergio.perez108@gmail.com', '1989-03-22', 41000),												
('Martha', 'Romero', 'Ríos', 'RORR900423MDFRZN19', 'RORR900423I59', '5510000109', 'F', 'martha.romero109@gmail.com', '1990-04-23', 36000),												
('Luis', 'Castillo', 'Santos', 'CALS910524HDFRZN11', 'CALS910524J60', '5510000110', 'M', 'luis.castillo110@gmail.com', '1991-05-24', 54000.25),												
('Rosa', 'Ortega', 'Rojas', 'ORRR920625MDFRZN11', 'ORRR920625K61', '5510000111', 'F', 'rosa.ortega111@gmail.com', '1992-06-25', 43000),												
('Arturo', 'Morales', 'Salas', 'MOSA930726HDFRZN11', 'MOSA930726L62', '5510000112', 'M', 'arturo.morales112@gmail.com', '1993-07-26', 49000.60),												
('Gabriela', 'Reyes', 'Hernández', 'REHG940827MDFRZN11', 'REHG940827M63', '5510000113', 'F', 'gabriela.reyes113@gmail.com', '1994-08-27', 39000),												
('Fernando', 'Sánchez', 'Luna', 'SALF950928HDFRZN11', 'SALF950928N64', '5510000114', 'M', 'fernando.sanchez114@gmail.com', '1995-09-28', 50000.40),												
('Claudia', 'Campos', 'Vega', 'CAVE961029MDFRZN11', 'CAVE961029O65', '5510000115', 'F', 'claudia.campos115@gmail.com', '1996-10-29', 37000),												
('Ricardo', 'Cruz', 'García', 'CRGR971130HDFRZN11', 'CRGR971130P66', '5510000116', 'M', 'ricardo.cruz116@gmail.com', '1997-11-30', 48000.75),												
('Elena', 'Rivas', 'Jiménez', 'RIJE690101MDFRZN11', 'RIJE690101Q67', '5510000117', 'F', 'elena.rivas117@gmail.com', '1969-01-01', 35000),												
('Francisco', 'Domínguez', 'Cruz', 'DOCF700202HDFRZN11', 'DOCF700202R68', '5510000118', 'M', 'francisco.dominguez118@gmail.com', '1970-02-02', 52000),												
('Lucía', 'Jiménez', 'Torres', 'JITL710303MDFRZN11', 'JITL710303S69', '5510000119', 'F', 'lucia.jimenez119@gmail.com', '1971-03-03', 32000),												
('Héctor', 'García', 'Ramos', 'GARE720404HDFRZN12', 'GARE720404T70', '5510000120', 'M', 'hector.garcia120@gmail.com', '1972-04-04', 47000.25),												
('Alejandra', 'Pineda', 'Salas', 'PISA730505MDFRZN12', 'PISA730505U71', '5510000121', 'F', 'alejandra.pineda121@gmail.com', '1973-05-05', 31000),												
('Ricardo', 'Mendoza', 'Jiménez', 'MEJR740606HDFRZN12', 'MEJR740606V72', '5510000122', 'M', 'ricardo.mendoza122@gmail.com', '1974-06-06', 47000.80),												
('Claudia', 'Campos', 'Ríos', 'CARI750707MDFRZN12', 'CARI750707W73', '5510000123', 'F', 'claudia.campos123@gmail.com', '1975-07-07', 36000),												
('Roberto', 'Cortés', 'Morales', 'COMR760808HDFRZN12', 'COMR760808X74', '5510000124', 'M', 'roberto.cortes124@gmail.com', '1976-08-08', 49000),												
('Gabriela', 'Delgado', 'Vega', 'DEVG770909MDFRZN12', 'DEVG770909Y75', '5510000125', 'F', 'gabriela.delgado125@gmail.com', '1977-09-09', 39000.90),												
('Antonio', 'Aguilar', 'Ramírez', 'AURR780110HDFRZN12', 'AURR780110Z76', '5510000126', 'M', 'antonio.aguilar126@gmail.com', '1978-01-10', 46000),												
('Daniela', 'Hernández', 'Cano', 'HECD790211MDFRZN12', 'HECD790211A77', '5510000127', 'F', 'daniela.hernandez127@gmail.com', '1979-02-11', 31000.40),												
('Eduardo', 'Gómez', 'Salas', 'GOSA800312HDFRZN12', 'GOSA800312B78', '5510000128', 'M', 'eduardo.gomez128@gmail.com', '1980-03-12', 47000),												
('Paola', 'Jiménez', 'Castro', 'JICP810413MDFRZN12', 'JICP810413C79', '5510000129', 'F', 'paola.jimenez129@gmail.com', '1981-04-13', 32000.50),												
('Óscar', 'Romero', 'Cano', 'ROCO820514HDFRZN13', 'ROCO820514D80', '5510000130', 'M', 'oscar.romero130@gmail.com', '1982-05-14', 43000),												
('Adriana', 'López', 'Ruiz', 'LORA830615MDFRZN13', 'LORA830615E81', '5510000131', 'F', 'adriana.lopez131@gmail.com', '1983-06-15', 38000.25),												
('Julio', 'Rojas', 'Pineda', 'ROPJ840716HDFRZN13', 'ROPJ840716F82', '5510000132', 'M', 'julio.rojas132@gmail.com', '1984-07-16', 47000),												
('Monserrat', 'Salas', 'Rivas', 'SARM850817MDFRZN33', 'SARM850817G83', '5510000133', 'F', 'monserrat.salas133@gmail.com', '1985-08-17', 31000),												
('Hugo', 'Carrillo', 'Núñez', 'CANH860918HDFRZN34', 'CANH860918H84', '5510000134', 'M', 'hugo.carrillo134@gmail.com', '1986-09-18', 49000.50),												
('Beatriz', 'Luna', 'Vega', 'LUVE870120MDFRZN13', 'LUVE870120I85', '5510000135', 'F', 'beatriz.luna135@gmail.com', '1987-01-20', 37000),												
('David', 'Morales', 'Pérez', 'MOPE880221HDFRZN13', 'MOPE880221J86', '5510000136', 'M', 'david.morales136@gmail.com', '1988-02-21', 46000.90),												
('Sandra', 'Delgado', 'Aguilar', 'DEAS890322MDFRZN13', 'DEAS890322K87', '5510000137', 'F', 'sandra.delgado137@gmail.com', '1989-03-22', 39000),												
('Ramiro', 'García', 'Jiménez', 'GAJR900423HDFRZN13', 'GAJR900423L88', '5510000138', 'M', 'ramiro.garcia138@gmail.com', '1990-04-23', 52000),												
('Cecilia', 'Reyes', 'Cano', 'RECC910524MDFRZN13', 'RECC910524M89', '5510000139', 'F', 'cecilia.reyes139@gmail.com', '1991-05-24', 33000),												
('Ernesto', 'Vega', 'Santos', 'VESA920625HDFRZN14', 'VESA920625N90', '5510000140', 'M', 'ernesto.vega140@gmail.com', '1992-06-25', 47000.50),												
('Clara', 'Torres', 'Campos', 'TOCC930726MDFRZN14', 'TOCC930726O91', '5510000141', 'F', 'clara.torres141@gmail.com', '1993-07-26', 35000),												
('Rafael', 'Núñez', 'Luna', 'NULR940827HDFRZN14', 'NULR940827P92', '5510000142', 'M', 'rafael.nunez142@gmail.com', '1994-08-27', 48000),												
('Lucero', 'Ramírez', 'Ortega', 'RAOL950928MDFRZN14', 'RAOL950928Q93', '5510000143', 'F', 'lucero.ramirez143@gmail.com', '1995-09-28', 36000.60),												
('Fernando', 'Ríos', 'Hernández', 'RIHF961029HDFRZN14', 'RIHF961029R94', '5510000144', 'M', 'fernando.rios144@gmail.com', '1996-10-29', 44000),												
('Rocío', 'Aguilar', 'Cruz', 'AGCR971130MDFRZN14', 'AGCR971130S95', '5510000145', 'F', 'rocio.aguilar145@gmail.com', '1997-11-30', 37000),												
('Ignacio', 'Soto', 'Vega', 'SOVE690101HDFRZN14', 'SOVE690101T96', '5510000146', 'M', 'ignacio.soto146@gmail.com', '1969-01-01', 55000.75),												
('Gloria', 'Mora', 'Campos', 'MOCA700202MDFRZN14', 'MOCA700202U97', '5510000147', 'F', 'gloria.mora147@gmail.com', '1970-02-02', 39000),												
('Esteban', 'Campos', 'Reyes', 'CARE710303HDFRZN14', 'CARE710303V98', '5510000148', 'M', 'esteban.campos148@gmail.com', '1971-03-03', 49000),												
('Marisol', 'Hernández', 'Salas', 'HESA720404MDFRZN14', 'HESA720404W99', '5510000149', 'F', 'marisol.hernandez149@gmail.com', '1972-04-04', 37000.40),												
('Omar', 'Castillo', 'Morales', 'CAMO730505HDFRZN15', 'CAMO730505X00', '5510000150', 'M', 'omar.castillo150@gmail.com', '1973-05-05', 47000);												


CREATE TABLE asignatura (
  clave_asignatura INT PRIMARY KEY,		-- Clave única de la asignatura
  nombre VARCHAR(80) NOT NULL UNIQUE	-- Nombre de la materia
);


-- ---------------------------------------------------------
-- Tabla: grupo
-- Representa los grupos académicos utilizados para organizar a los alumnos.
-- Se hizo esta tabla mas que nada para evitar redundancia y porque un grupo tiene muchos cursos
-- ---------------------------------------------------------

INSERT INTO asignatura (clave_asignatura, nombre) VALUES				
(2122,'Administración'),				
(2124,'Desarrollo sostenible en las organizaciones'),				
(2125,'Diseño de algoritmos'),				
(2126,'Ética en las organizaciones'),				
(2129,'Fundamentos de informática'),				
(2130,'Fundamentos para el análisis cuantitativo'),				
(2134,'Principios y técnicas de investigación'),				
(2222,'Administración de requerimientos'),				
(2227,'Entorno de las organizaciones'),				
(2229,'Infraestructura informática'),				
(2233,'Operaciones'),				
(2237,'Programación'),				
(2135,'Razonamiento lógico matemático para la toma de decisiones'),				
(2137,'Teoría del conocimiento'),				
(2324,'Análisis y diseño de sistemas'),				
(2325,'Arquitectura de computadoras'),				
(2331,'Estructura de datos'),				
(2131,'Género y derechos humanos en las organizaciones'),				
(2333,'Matemáticas discretas'),				
(2337,'Recursos humanos'),				
(2422,'Contabilidad'),				
(2425,'Diseño de bases de datos relacionales'),				
(2426,'Estadística descriptiva e inferencial'),				
(2128,'Fundamentos de derecho'),				
(2232,'Mercadotecnia'),				
(2430,'Programación orientada a objetos'),				
(2433,'Sistemas operativos multiusuarios'),				
(2523,'Administración de la función informática'),				
(2527,'Cálculo diferencial e integral'),				
(2529,'Derecho informático'),				
(2533,'Implementación de sistemas'),				
(2231,'Matemáticas financieras'),				
(2537,'Sistemas manejadores de bases de datos relacionales'),				
(2539,'Telecomunicaciones I'),				
(2629,'Desarrollo de aplicaciones móviles'),				
(2630,'Desarrollo de aplicaciones web'),				
(2631,'Entorno estratégico de tecnologías de información'),				
(2632,'Finanzas'),				
(2635,'Investigación de operaciones'),				
(2638,'Telecomunicaciones II'),				
(2726,'Costos y presupuestos'),				
(2728,'Ingeniería de software'),				
(2730,'Negocios digitales'),				
(2732,'Planeación de proyectos informáticos'),				
(2733,'Seguridad informática'),				
(2824,'Auditoría informática'),				
(2828,'Servicios de tecnología');				

-- ----


CREATE TABLE grupo (
  id_grupo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del grupo
  nombre_grupo CHAR(4) NOT NULL UNIQUE							-- Nombre o clave del grupo
);

-- ---------------------------------------------------------
-- Tabla: tipo_curso
-- Define la modalidad del curso (ej. Ordinario, Extraordinario, Intersemestral).	
-- Se hizo esta tabla mas que nada para evitar redundancia y tambien porque hay muchos cursos con el mismo tipo 
-- ---------------------------------------------------------

INSERT INTO grupo (nombre_grupo) VALUES			
('1596'),('1597'),('1598'),('1599'),('1600'),			
('1601'),('1602'),('1603'),('1604'),('1605'),			
('EE51'),('EE52'),('EE53'),('EE54'),('EE55'),			
('EE56'),('EE57'),('EE58'),('EE59'),('EE60'),			
('1616'),('1617'),('1618'),('1619'),('1620'),			
('1621'),('1622'),('1623'),('1624'),('1625'),			
('1626'),('1627'),('1628'),('1629'),('1630'),			
('1631'),('1632'),('1633'),('1634'),('1635'),			
('1636'),('1637'),('1638'),('1639'),('1640'),			
('1641'),('1642'),('1643'),('1644'),('1645');	


CREATE TABLE tipo_curso (
  id_tipo_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del tipo
  nombre_tipo   VARCHAR(40) NOT NULL UNIQUE							-- Nombre del tipo de curso
);

-- ---------------------------------------------------------
-- Tabla: periodo_academico
-- Define los periodos escolares en los que se imparten los cursos (ej. 2025-1, 2025-2).
-- Se hizo esta tabla mas que nada para evitar redundancia y tambien porque varios semestres tienen el mismo periodo.
-- ---------------------------------------------------------

INSERT INTO tipo_curso (nombre_tipo) VALUES			
('Ordinario'),			
('Extraordinario'),			
('Intersemestral');		


CREATE TABLE periodo_academico (
  id_periodo     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del periodo
  periodo_nombre VARCHAR(8) NOT NULL UNIQUE,						-- Nombre del periodo
  fecha_inicio   DATE NOT NULL,										-- Fecha de inicio
  fecha_fin      DATE NOT NULL,										-- Fecha de fin
  
  -- Validación de rango de fechas
  CONSTRAINT ck_periodo_fechas CHECK (fecha_inicio < fecha_fin)
);



INSERT INTO periodo_academico (periodo_nombre, fecha_inicio, fecha_fin) VALUES					
('2025-1', '2024-08-05', '2025-02-04'),					
('2025-2', '2025-02-05', '2025-08-04'),					
('2026-1', '2025-08-05', '2026-02-04'),					
('2026-2', '2026-02-05', '2026-08-04'),					
('2027-1', '2026-08-05', '2027-02-04'),					
('2027-2', '2027-02-05', '2027-08-04'),					
('2028-1', '2027-08-05', '2028-02-04'),					
('2028-2', '2028-02-05', '2028-08-04'),					
('2029-1', '2028-08-05', '2029-02-04'),					
('2029-2', '2029-02-05', '2029-08-04'),					
('2030-1', '2029-08-05', '2030-02-04'),					
('2030-2', '2030-02-05', '2030-08-04'),					
('2031-1', '2030-08-05', '2031-02-04'),					
('2031-2', '2031-02-05', '2031-08-04'),					
('2032-1', '2031-08-05', '2032-02-04'),					
('2032-2', '2032-02-05', '2032-08-04'),					
('2033-1', '2032-08-05', '2033-02-04'),					
('2033-2', '2033-02-05', '2033-08-04'),					
('2034-1', '2033-08-05', '2034-02-04'),					
('2034-2', '2034-02-05', '2034-08-04'),					
('2035-1', '2034-08-05', '2035-02-04'),					
('2035-2', '2035-02-05', '2035-08-04'),					
('2036-1', '2035-08-05', '2036-02-04'),					
('2036-2', '2036-02-05', '2036-08-04'),					
('2037-1', '2036-08-05', '2037-02-04'),					
('2037-2', '2037-02-05', '2037-08-04'),					
('2038-1', '2037-08-05', '2038-02-04'),					
('2038-2', '2038-02-05', '2038-08-04'),					
('2039-1', '2038-08-05', '2039-02-04'),					
('2039-2', '2039-02-05', '2039-08-04'),					
('2040-1', '2039-08-05', '2040-02-04'),					
('2040-2', '2040-02-05', '2040-08-04'),					
('2041-1', '2040-08-05', '2041-02-04'),					
('2041-2', '2041-02-05', '2041-08-04'),					
('2042-1', '2041-08-05', '2042-02-04'),					
('2042-2', '2042-02-05', '2042-08-04'),					
('2043-1', '2042-08-05', '2043-02-04'),					
('2043-2', '2043-02-05', '2043-08-04'),					
('2044-1', '2043-08-05', '2044-02-04'),					
('2044-2', '2044-02-05', '2044-08-04'),					
('2045-1', '2044-08-05', '2045-02-04'),					
('2045-2', '2045-02-05', '2045-08-04'),					
('2046-1', '2045-08-05', '2046-02-04'),					
('2046-2', '2046-02-05', '2046-08-04'),					
('2047-1', '2046-08-05', '2047-02-04'),					
('2047-2', '2047-02-05', '2047-08-04'),					
('2048-1', '2047-08-05', '2048-02-04'),					
('2048-2', '2048-02-05', '2048-08-04'),					
('2049-1', '2048-08-05', '2049-02-04'),					
('2049-2', '2049-02-05', '2049-08-04');			

-- ---------------------------------------------------------
-- Tabla: nivel_semestre
-- Catálogo de niveles o semestres académicos (ej. Primero, Segundo, Tercero, etc).
-- Se hizo esta tabla mas que nada para evitar redunancia. 
-- ---------------------------------------------------------

CREATE TABLE nivel_semestre (
  id_nivel_semestre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del nivel
  nombre_semestre   VARCHAR(12) NOT NULL UNIQUE							-- Nombre del semestre
);


INSERT INTO nivel_semestre (nombre_semestre) VALUES				
('primero'),				
('segundo'),				
('tercero'),				
('cuarto'),				
('quinto'),				
('sexto'),				
('septimo'),				
('octavo'),				
('noveno'),				
('decimo');	

-- ---------------------------------------------------------
-- Tabla: oferta_semestral
-- Representa la ENTIDAD SEMESTRES del modelo lógico.
-- En el modelo físico esa entidad se materializa como la tabla oferta_semestral,
-- junto con sus llaves foráneas hacia periodo_academico y nivel_semestre.
-- Cada fila es un semestre concreto (ej. "Primer semestre 2025-1"),
-- resultado de combinar:
--   - el nivel del semestre (nivel_semestre)
--   - con el periodo académico (periodo_academico).

-- ---------------------------------------------------------

CREATE TABLE oferta_semestral (
  id_oferta_semestral INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador de la oferta
  id_periodo          INT NOT NULL,											-- Periodo académico
  id_nivel_semestre   INT NOT NULL,											-- Nivel o semestre

-- Relación con periodo_academico
  CONSTRAINT fk_oferta_periodo
    FOREIGN KEY (id_periodo)
    REFERENCES periodo_academico(id_periodo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

-- Relación con nivel_semestre
  CONSTRAINT fk_oferta_nivel
    FOREIGN KEY (id_nivel_semestre)
    REFERENCES nivel_semestre(id_nivel_semestre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

-- Evita duplicar ofertas del mismo periodo y semestre
  CONSTRAINT uq_oferta_periodo_nivel UNIQUE (id_periodo, id_nivel_semestre)
);


INSERT INTO oferta_semestral (id_periodo, id_nivel_semestre) VALUES					
-- Periodo 1					
(1,1),(1,3),(1,5),(1,7),(1,9),					
-- Periodo 2					
(2,2),(2,4),(2,6),(2,8),(2,10),					
-- Periodo 3					
(3,1),(3,3),(3,5),(3,7),(3,9),					
-- Periodo 4					
(4,2),(4,4),(4,6),(4,8),(4,10),					
-- Periodo 5					
(5,1),(5,3),(5,5),(5,7),(5,9),					
					
(6,2),(6,4),(6,6),(6,8),(6,10),					
					
(7,1),(7,3),(7,5),(7,7),(7,9),					
					
(8,2),(8,4),(8,6),(8,8),(8,10),					
					
(9,1),(9,3),(9,5),(9,7),(9,9),					
					
(10,2),(10,4),(10,6),(10,8),(10,10);		


INSERT INTO plantel (nombre_plantel) VALUES			
('Facultad de Contaduría y Administración');			

-- ---------------------------------------------------------
-- INSERCIÓN DE: credito
-- Define los tipos de créditos académicos que pueden obtener los alumnos al aprobar cursos.
-- Estos créditos forman parte del historial académico y del avance curricular del estudiante.
-- ---------------------------------------------------------

INSERT INTO credito (tipo_credito, punto_credito) VALUES	
('OBL', 8),	
('OPT', 12);	



INSERT INTO horario (dia, hora_inicio, hora_fin) VALUES				
('Lunes','07:00','09:00'),				
('Lunes','09:00','11:00'),				
('Lunes','11:00','13:00'),				
('Lunes','13:00','15:00'),				
('Lunes','15:00','17:00'),				
('Lunes','17:00','19:00'),				
('Lunes','19:00','21:00'),				
('Lunes','21:00','23:00'),				
('Martes','07:00','09:00'),				
('Martes','09:00','11:00'),				
('Martes','11:00','13:00'),				
('Martes','13:00','15:00'),				
('Martes','15:00','17:00'),				
('Martes','17:00','19:00'),				
('Martes','19:00','21:00'),				
('Martes','21:00','23:00'),				
('Miercoles','07:00','09:00'),				
('Miercoles','09:00','11:00'),				
('Miercoles','11:00','13:00'),				
('Miercoles','13:00','15:00'),				
('Miercoles','15:00','17:00'),				
('Miercoles','17:00','19:00'),				
('Miercoles','19:00','21:00'),				
('Miercoles','21:00','23:00'),				
('Jueves','07:00','09:00'),				
('Jueves','09:00','11:00'),				
('Jueves','11:00','13:00'),				
('Jueves','13:00','15:00'),				
('Jueves','15:00','17:00'),				
('Jueves','17:00','19:00'),				
('Jueves','19:00','21:00'),				
('Jueves','21:00','23:00'),				
('Viernes','07:00','09:00'),				
('Viernes','09:00','11:00'),				
('Viernes','11:00','13:00'),				
('Viernes','13:00','15:00'),				
('Viernes','15:00','17:00'),				
('Viernes','17:00','19:00'),				
('Viernes','19:00','21:00'),				
('Viernes','21:00','23:00'),				
('Sabado','07:00','09:00'),				
('Sabado','09:00','11:00'),				
('Sabado','11:00','13:00'),				
('Sabado','13:00','15:00'),				
('Sabado','15:00','17:00'),				
('Sabado','17:00','19:00'),				
('Sabado','19:00','21:00'),				
('Sabado','21:00','23:00'),				
('Sabado','01:00','3:00'),				
('Sabado','03:00','5:00');


INSERT INTO salon (nombre_salon) VALUES		
('K102'),('K103'),('K104'),('K105'),('K106'),		
('K107'),('K108'),('K109'),('K110'),('K111'),		
('K112'),('K113'),('K114'),('K115'),('K116'),		
('K117'),('K118'),('K119'),('K120'),('K121'),		
('K122'),('K123'),('K124'),('K125'),('K126'),		
('D203'),('D204'),('D205'),('D206'),('D207'),		
('D208'),('D209'),('D210'),('D211'),('D212'),		
('D213'),('D214'),('D215'),('D216'),('D217'),		
('D218'),('D219'),('D220'),('D221'),('D222'),		
('D223'),('D224'),('D225'),('D226'),('D227');		




-- ---------------------------------------------------------
-- Tabla: curso
-- Representa un curso específico (asignatura + profesor + grupo + semestre).
--
-- Campo adicional: inscritos_actual
--   - Agregamos este campo para llevar un contador del número de alumnos
--     inscritos en cada curso.
--   - Un trigger (trg_inscritos) se dispara cuando se inserta o elimina un
--     registro en alumno_curso y actualiza este contador automáticamente.
--   - El procedimiento sp_inscribir_alumno_cupo usa cupo_maximo e
--     inscritos_actual para validar que no se exceda el cupo cuando se intenta
--     inscribir a un alumno.
-- ---------------------------------------------------------


CREATE TABLE curso (
  id_curso            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del curso
  cupo_maximo         INT NOT NULL,										-- Cupo máximo permitido
  inscritos_actual    INT NOT NULL DEFAULT 0,							-- Alumnos inscritos actualmente
  id_profesor         INT NOT NULL,										-- Profesor a cargo
  clave_asignatura    INT NOT NULL,										-- Asignatura impartida
  id_oferta_semestral INT NOT NULL,										-- Oferta semestral
  id_tipo_curso       INT NOT NULL,										-- Tipo o modalidad del curso
  id_grupo            INT NOT NULL,										-- Grupo asignado

-- Restricciones de validación
  CONSTRAINT ck_curso_cupo     CHECK (cupo_maximo > 0),
  CONSTRAINT ck_curso_inscritos CHECK (inscritos_actual >= 0),

-- Relaciones con catálogos y entidades principales
  CONSTRAINT fk_curso_profesor
    FOREIGN KEY (id_profesor)
    REFERENCES profesor(id_profesor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_asignatura
    FOREIGN KEY (clave_asignatura)
    REFERENCES asignatura(clave_asignatura)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_oferta
    FOREIGN KEY (id_oferta_semestral)
    REFERENCES oferta_semestral(id_oferta_semestral)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_tipo
    FOREIGN KEY (id_tipo_curso)
    REFERENCES tipo_curso(id_tipo_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_grupo
    FOREIGN KEY (id_grupo)
    REFERENCES grupo(id_grupo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- ---------------------------------------------------------
-- Tabla: horario
-- Define los horarios disponibles para impartir cursos, incluyendo día de la semana y rango de horas.
-- ---------------------------------------------------------

CREATE TABLE horario (
  id_horario  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador del horario
  dia         VARCHAR(10) NOT NULL,									-- Día de la semana
  hora_inicio TIME NOT NULL,										-- Hora de inicio
  hora_fin    TIME NOT NULL,										-- Hora de fin
  
  -- Validaciones de horario
  CONSTRAINT ck_horario_horas CHECK (hora_inicio < hora_fin),
  CONSTRAINT ck_horario_dia CHECK (dia IN ('Lunes','Martes','Miercoles','Jueves','Viernes','Sabado'))
);



INSERT INTO horario (dia, hora_inicio, hora_fin) VALUES				
('Lunes','07:00','09:00'),				
('Lunes','09:00','11:00'),				
('Lunes','11:00','13:00'),				
('Lunes','13:00','15:00'),				
('Lunes','15:00','17:00'),				
('Lunes','17:00','19:00'),				
('Lunes','19:00','21:00'),				
('Lunes','21:00','23:00'),				
('Martes','07:00','09:00'),				
('Martes','09:00','11:00'),				
('Martes','11:00','13:00'),				
('Martes','13:00','15:00'),				
('Martes','15:00','17:00'),				
('Martes','17:00','19:00'),				
('Martes','19:00','21:00'),				
('Martes','21:00','23:00'),				
('Miercoles','07:00','09:00'),				
('Miercoles','09:00','11:00'),				
('Miercoles','11:00','13:00'),				
('Miercoles','13:00','15:00'),				
('Miercoles','15:00','17:00'),				
('Miercoles','17:00','19:00'),				
('Miercoles','19:00','21:00'),				
('Miercoles','21:00','23:00'),				
('Jueves','07:00','09:00'),				
('Jueves','09:00','11:00'),				
('Jueves','11:00','13:00'),				
('Jueves','13:00','15:00'),				
('Jueves','15:00','17:00'),				
('Jueves','17:00','19:00'),				
('Jueves','19:00','21:00'),				
('Jueves','21:00','23:00'),				
('Viernes','07:00','09:00'),				
('Viernes','09:00','11:00'),				
('Viernes','11:00','13:00'),				
('Viernes','13:00','15:00'),				
('Viernes','15:00','17:00'),				
('Viernes','17:00','19:00'),				
('Viernes','19:00','21:00'),				
('Viernes','21:00','23:00'),				
('Sabado','07:00','09:00'),				
('Sabado','09:00','11:00'),				
('Sabado','11:00','13:00'),				
('Sabado','13:00','15:00'),				
('Sabado','15:00','17:00'),				
('Sabado','17:00','19:00'),				
('Sabado','19:00','21:00'),				
('Sabado','21:00','23:00'),				
('Sabado','01:00','3:00'),				
('Sabado','03:00','5:00');	




INSERT INTO asignacion_curso (id_horario, id_curso, id_salon) VALUES
-- Cursos 1–7 (patrón L-Mi / Ma-Ju)
(3, 1, 26), (19, 1, 26),
(11,2, 27), (27,2, 27),
(2, 3, 1 ), (18,3, 1 ),
(10,4, 28), (26,4, 28),
(1, 5, 29), (17,5, 29),
(9, 6, 30), (25,6, 30),
(4, 7, 31), (20,7, 31),
(5, 8, 2 ), (21,8, 2 ),
(13,9, 3 ), (29,9, 3 ),
(6, 10,4 ), (22,10,4 ),
(14,11,5 ), (30,11,5 ),
(7, 12,6 ), (23,12,6 ),
(15,13,7 ), (31,13,7 ),
(43,14,8 ), (44,14,8 ),
(16,15,32), (32,15,32),
(8, 16,33), (24,16,33),
(15,17,34), (31,17,34),
(7, 18,35), (23,18,35),
(14,19,36), (30,19,36),
(6, 20,37), (22,20,37),
(13,21,38), (29,21,38),
(5, 22,39), (21,22,39),
(44,23,40), (45,23,40),
(46,24,41), (47,24,41),
(3, 25,9), (19,25,9);



INSERT INTO alumno_curso
(primer_parcial, segundo_parcial, tercer_parcial, estatus_evaluacion, numero_cuenta, id_curso)
VALUES
-- Alumno 320267695 (4 materias)
(8.0, 8.5, 9.0,  'REG', 320267695, 1),
(7.0, 7.8, 8.2,  'REG', 320267695, 2),
(6.5, NULL, NULL,'REG', 320267695, 8),
(NULL,NULL,NULL, 'NP',  320267695, 15),

-- Alumno 320267696 (4 materias)
(9.0, 9.2, 9.6,  'REG', 320267696, 1),
(8.2, 8.6, 9.0,  'REG', 320267696, 3),
(7.4, NULL, NULL,'REG', 320267696, 9),
(6.0, 5.8, 5.5,  'REG', 320267696, 16),

-- Alumno 320267697 (4 materias)
(8.5, 8.8, 9.1,  'REG', 320267697, 2),
(7.3, 7.6, 8.0,  'REG', 320267697, 4),
(7.0, NULL, NULL,'REG', 320267697, 10),
(NULL,NULL,NULL, 'NP',  320267697, 17),

-- Alumno 320267698 (4 materias)
(7.8, 8.1, 8.4,  'REG', 320267698, 3),
(6.2, 6.0, 5.9,  'REG', 320267698, 5),
(8.6, NULL, NULL,'REG', 320267698, 11),
(7.0, 7.2, 7.5,  'REG', 320267698, 18),

-- Alumno 320267699 (4 materias)
(8.0, 8.4, 8.7,  'REG', 320267699, 4),
(7.1, 7.5, 7.9,  'REG', 320267699, 6),
(6.9, NULL, NULL,'REG', 320267699, 12),
(NULL,NULL,NULL, 'NP',  320267699, 19),

-- Alumno 320267700 (4 materias)
(9.0, 9.4, 9.8,  'REG', 320267700, 5),
(8.5, 8.9, 9.2,  'REG', 320267700, 7),
(7.6, NULL, NULL,'REG', 320267700, 13),
(6.5, 6.1, 5.7,  'REG', 320267700, 20),

-- Alumno 320267701 (4 materias)
(7.7, 8.0, 8.3,  'REG', 320267701, 6),
(8.2, 8.5, 8.8,  'REG', 320267701, 8),
(6.8, NULL, NULL,'REG', 320267701, 14),
(NULL,NULL,NULL, 'NP',  320267701, 21),

-- Alumno 320267702 (4 materias)
(8.4, 8.7, 9.0,  'REG', 320267702, 7),
(7.0, 7.3, 7.6,  'REG', 320267702, 9),
(7.2, NULL, NULL,'REG', 320267702, 15),
(6.0, 6.0, 6.0,  'REG', 320267702, 22),

-- Alumno 320267703 (4 materias)
(7.9, 8.2, 8.6,  'REG', 320267703, 8),
(8.8, 9.1, 9.5,  'REG', 320267703, 10),
(6.4, NULL, NULL,'REG', 320267703, 16),
(NULL,NULL,NULL, 'NP',  320267703, 23),

-- Alumno 320267704 (4 materias)
(9.2, 9.5, 9.8,  'REG', 320267704, 9),
(7.5, 7.8, 8.1,  'REG', 320267704, 11),
(7.0, NULL, NULL,'REG', 320267704, 17),
(6.1, 5.9, 5.6,  'REG', 320267704, 24),

-- Alumno 320267705 (4 materias)
(8.1, 8.4, 8.7,  'REG', 320267705, 10),
(7.2, 7.5, 7.8,  'REG', 320267705, 12),
(6.6, NULL, NULL,'REG', 320267705, 18),
(NULL,NULL,NULL, 'NP',  320267705, 25),

-- Alumno 320267706 (3 materias)
(7.0, NULL, NULL,'REG', 320267706, 11),
(8.0, 8.4, 8.9,  'REG', 320267706, 13),
(6.0, 5.7, 5.4,  'REG', 320267706, 19),

-- Alumno 320267707 (3 materias)
(8.3, NULL, NULL,'REG', 320267707, 12),
(7.6, 7.9, 8.2,  'REG', 320267707, 14),
(NULL,NULL,NULL, 'NP',  320267707, 20);

-- ---------------------------------------------------------
-- Tabla: salon
-- Catálogo de salones físicos donde se imparten los cursos.
-- Esta tabla existe porque un curso puede tener varios salones y un salon puede tener varios cursos
-- Entonces se generaba mucha redundancia 
-- ---------------------------------------------------------

CREATE TABLE salon (
  id_salon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del salón
  nombre_salon VARCHAR(20) NOT NULL UNIQUE						-- Nombre o clave del salón
);

-- ---------------------------------------------------------
-- Tabla: asignacion_curso 
-- es una tabla intermedia que relaciona
--       curso + horario + salón.
--     Cada fila significa: "el curso X se imparte en el salón Y en el horario Z".
--
-- Con la restricción UNIQUE (id_horario, id_salon) en `asignacion_curso`
-- evitamos que haya dos cursos al mismo tiempo en el mismo salón.
-- Además, permitimos que:
--   - un mismo curso pueda tener varios horarios/salones (varias filas),
--   - y un mismo salón se use en diferentes horarios sin empalmes.
-- ---------------------------------------------------------

CREATE TABLE asignacion_curso (
  id_asignacion_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador de la asignación
  id_horario INT NOT NULL,												-- Horario asignado
  id_curso   INT NOT NULL,												-- Curso asignado
  id_salon   INT NOT NULL,												-- Salón asignado

-- Relaciones
  CONSTRAINT fk_asig_horario FOREIGN KEY (id_horario)
    REFERENCES horario(id_horario)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_asig_curso FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_asig_salon FOREIGN KEY (id_salon)
    REFERENCES salon(id_salon)
    ON DELETE RESTRICT ON UPDATE CASCADE,

-- Evita que un salón tenga dos cursos al mismo horario
  CONSTRAINT uq_asig_horario_salon UNIQUE (id_horario, id_salon)
);

-- ---------------------------------------------------------
-- Tabla: alumno_curso
-- Registra la inscripción de alumnos a cursos y sus evaluaciones parciales.
--
-- Campo: estatus_evaluacion
--   - Indica en qué situación quedó la evaluación del alumno en ese curso.
--   - Usamos dos valores:
--       'REG' → Alumno regular (cursó normalmente).
--       'NP'  → No presentó / no terminó la materia.
--   - Por defecto es 'REG'.
--   - Cuando es 'NP', los triggers se encargan de limpiar las calificaciones
--     parciales y evitar que se calcule un promedio final.
-- ---------------------------------------------------------

CREATE TABLE alumno_curso (
  id_alumno_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador de la inscripción
  primer_parcial  NUMERIC(4,2) NULL,								-- Calificación primer parcial
  segundo_parcial NUMERIC(4,2) NULL,								-- Calificación segundo parcial
  tercer_parcial  NUMERIC(4,2) NULL,								-- Calificación tercer parcial
  estatus_evaluacion VARCHAR(3) NOT NULL DEFAULT 'REG',				-- Estatus de evaluación
  numero_cuenta   INT NOT NULL,										-- Alumno inscrito
  id_curso        INT NOT NULL,										-- Curso inscrito

-- Evita inscripciones duplicadas
  CONSTRAINT uq_alumno_curso UNIQUE (numero_cuenta, id_curso),

-- Validaciones de calificaciones
  CONSTRAINT ck_p1 CHECK (primer_parcial  IS NULL OR (primer_parcial  BETWEEN 0 AND 10)),
  CONSTRAINT ck_p2 CHECK (segundo_parcial IS NULL OR (segundo_parcial BETWEEN 0 AND 10)),
  CONSTRAINT ck_p3 CHECK (tercer_parcial  IS NULL OR (tercer_parcial  BETWEEN 0 AND 10)),
  CONSTRAINT ck_estatus_final CHECK (estatus_evaluacion IN ('REG','NP')),

-- Regla: si es NP no puede haber calificaciones
  CONSTRAINT ck_np_sin_notas CHECK (
    (estatus_evaluacion = 'REG')
    OR
    (estatus_evaluacion = 'NP'
      AND primer_parcial  IS NULL
      AND segundo_parcial IS NULL
      AND tercer_parcial  IS NULL)
  ),

-- Relaciones
  CONSTRAINT fk_ac_alumno FOREIGN KEY (numero_cuenta)
    REFERENCES alumno(numero_cuenta)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_ac_curso FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ---------------------------------------------------------
-- Tabla: plantel
-- Catálogo de planteles o sedes de la institución.
-- Esta tabla nada mas la agregamos para simular el historial del SIAE
-- Nada mas se agrego una facultad
-- ---------------------------------------------------------

CREATE TABLE plantel (
  clave_plantel INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 	-- Identificador del plantel
  nombre_plantel VARCHAR(150) NOT NULL UNIQUE						-- Nombre del plantel
);

-- ---------------------------------------------------------
-- Tabla: credito
-- Define los tipos de créditos académicos que puede obtener un alumno.
-- Esta tabla nada mas la agregamos para simular el historial del SIAE
-- ---------------------------------------------------------

CREATE TABLE credito (
  id_credito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,		-- Identificador del crédito
  tipo_credito CHAR(3) NOT NULL,									-- Tipo (OBL/OPT)
  punto_credito INT NOT NULL,										-- Valor en créditos
  
  -- Validaciones
  CONSTRAINT ck_credito_puntos CHECK (punto_credito > 0),
  CONSTRAINT ck_credito_tipo   CHECK (tipo_credito IN ('OBL','OPT'))
);

-- ---------------------------------------------------------
-- Tabla: historial
-- Guarda el registro "oficial" de la calificación final de una inscripción
-- (lo que sería el historial académico / acta de calificaciones).
--
-- Campo: folio_acta
--   - Es un identificador alfanumérico del acta donde quedó registrada
--     la calificación del alumno en ese curso.
--   - Se genera automáticamente en los triggers con el formato
--     'AC' + id_alumno_curso con ceros a la izquierda (ej. 'AC00000017').
--   - Es UNIQUE, para que cada acta tenga un folio distinto y sea fácil
--     de localizar o referenciar en reportes.
-- ---------------------------------------------------------

CREATE TABLE historial (
  id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- Identificador del historial
  folio_acta VARCHAR(10) NOT NULL UNIQUE,							-- Folio del acta
  id_alumno_curso INT NOT NULL,										-- Inscripción evaluada
  id_credito INT NOT NULL,											-- Crédito asociado
  clave_plantel INT NOT NULL,										-- Plantel correspondiente
  promedio_final NUMERIC(4,2) NULL,									-- Promedio final

-- Un historial por inscripción
  CONSTRAINT uq_hist_ac UNIQUE (id_alumno_curso),

  CONSTRAINT fk_hist_ac FOREIGN KEY (id_alumno_curso)
    REFERENCES alumno_curso(id_alumno_curso)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_hist_credito FOREIGN KEY (id_credito)
    REFERENCES credito(id_credito)
    ON DELETE RESTRICT ON UPDATE CASCADE,

  CONSTRAINT fk_hist_plantel FOREIGN KEY (clave_plantel)
    REFERENCES plantel(clave_plantel)
    ON DELETE RESTRICT ON UPDATE CASCADE
);


SELECT * FROM entidad_federativa 
SELECT * FROM alumno 
SELECT * FROM profesor 
SELECT * FROM asignatura 
SELECT * FROM grupo 
SELECT * FROM tipo_curso 
SELECT * FROM periodo_academico 
SELECT * FROM nivel_semestre 
SELECT * FROM oferta_semestral 
SELECT * FROM curso 
SELECT * FROM horario 
SELECT * FROM salon 
SELECT * FROM asignacion_curso 
SELECT * FROM alumno_curso 
SELECT * FROM plantel 
SELECT * FROM credito 
SELECT * FROM historial 

